export enum OrderStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  CLOSED_UNPAID = 'CLOSED_UNPAID',
  DELIVERED = 'DELIVERED',
  COMPLETED = 'COMPLETED',
  AFTERSALE = 'AFTERSALE',
  REFUNDED = 'REFUNDED',
  CANCELLED = 'CANCELLED',

  PENDING_MERCHANT = 'PENDING_MERCHANT',
  MERCHANT_REJECTED = 'MERCHANT_REJECTED',
  MERCHANT_TIMEOUT = 'MERCHANT_TIMEOUT',
  PENDING_RIDER = 'PENDING_RIDER',
  PENDING_PICKUP = 'PENDING_PICKUP',
  DELIVERING = 'DELIVERING',

  PENDING_REVIEW = 'PENDING_REVIEW',
  PENDING_DISPATCH = 'PENDING_DISPATCH',
  RIDER_ACCEPTED = 'RIDER_ACCEPTED',
  ON_THE_WAY = 'ON_THE_WAY',
  IN_PROGRESS = 'IN_PROGRESS',
}

export enum OrderType {
  PRODUCT = 'PRODUCT',
  ERRAND = 'ERRAND',
}

export enum ErrandServiceType {
  DELIVER = 'DELIVER',
  PICKUP = 'PICKUP',
  BUY = 'BUY',
  ERRAND = 'ERRAND',
}

export enum PaymentStatus {
  UNPAID = 'UNPAID',
  PAYING = 'PAYING',
  PAID = 'PAID',
  REFUNDING = 'REFUNDING',
  PARTIAL_REFUNDED = 'PARTIAL_REFUNDED',
  FULL_REFUNDED = 'FULL_REFUNDED',
  PAY_FAILED = 'PAY_FAILED',
}

export enum SettlementStatus {
  UNSETTLED = 'UNSETTLED',
  FROZEN = 'FROZEN',
  SETTLED = 'SETTLED',
  WITHDRAWN = 'WITHDRAWN',
}

export enum AftersaleStatus {
  PENDING_ACCEPT = 'PENDING_ACCEPT',
  PROCESSING = 'PROCESSING',
  PENDING_REFUND = 'PENDING_REFUND',
  REFUNDED = 'REFUNDED',
  REJECTED = 'REJECTED',
  CLOSED = 'CLOSED',
}

export enum UserRole {
  USER = 'USER',
  MERCHANT = 'MERCHANT',
  RIDER = 'RIDER',
  ADMIN = 'ADMIN',
}

export enum AccountStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  FROZEN = 'FROZEN',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum AuditStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum OnlineStatus {
  ONLINE = 'ONLINE',
  OFFLINE = 'OFFLINE',
  BUSY = 'BUSY',
}

export enum SmsScene {
  LOGIN = 'LOGIN',
  REGISTER = 'REGISTER',
  BIND_PHONE = 'BIND_PHONE',
  RESET_PASSWORD = 'RESET_PASSWORD',
}

export enum ClientType {
  MINIAPP = 'miniapp',
  WXAPP = 'wxapp',
  MERCHANT_APP = 'merchant-app',
  RIDER_APP = 'rider-app',
  ADMIN_WEB = 'admin-web',
}

export enum ErrorCode {
  SUCCESS = 0,

  PARAM_INVALID = 10001,
  DATA_NOT_FOUND = 10002,
  DATA_ALREADY_EXISTS = 10003,
  OPERATION_FAILED = 10004,
  SERVER_ERROR = 10005,

  RATE_LIMIT_EXCEEDED = 10100,
  REQUEST_FORMAT_ERROR = 10101,
  METHOD_NOT_ALLOWED = 10102,

  NOT_LOGGED_IN = 11001,
  TOKEN_INVALID = 11002,
  PERMISSION_DENIED = 11003,
  ACCOUNT_FROZEN = 11004,
  VERIFY_CODE_ERROR = 11005,
  TOO_FREQUENT = 11006,
  DAILY_LIMIT_REACHED = 11007,

  USER_PHONE_ALREADY_BOUND = 12001,
  USER_WX_AUTH_FAILED = 12002,
  USER_ADDRESS_LIMIT = 12003,
  USER_ADDRESS_NOT_FOUND = 12004,
  USER_ADDRESS_FORBIDDEN = 12005,

  MERCHANT_NOT_FOUND = 13001,
  MERCHANT_PASSWORD_ERROR = 13002,
  MERCHANT_FROZEN = 13003,
  MERCHANT_PHONE_REGISTERED = 13004,
  MERCHANT_AUDIT_NOT_PASSED = 13005,
  STORE_NOT_FOUND = 13006,
  STORE_FORBIDDEN = 13007,
  STORE_STATUS_INVALID = 13008,

  RIDER_NOT_FOUND = 14001,
  RIDER_PASSWORD_ERROR = 14002,
  RIDER_FROZEN = 14003,
  RIDER_PHONE_REGISTERED = 14004,
  RIDER_AUDIT_NOT_PASSED = 14005,
  RIDER_NOT_ONLINE = 14006,

  PRODUCT_STOCK_NOT_ENOUGH = 15001,
  PRODUCT_NOT_FOUND = 15002,
  SKU_NOT_FOUND = 15003,
  PRODUCT_OFF_SHELF = 15004,
  CATEGORY_NOT_FOUND = 15005,
  CATEGORY_HAS_PRODUCTS = 15006,
  PRODUCT_FORBIDDEN = 15007,

  STORE_CLOSED = 16001,
  ADDRESS_OUT_OF_RANGE = 16002,
  UNDER_MIN_ORDER_AMOUNT = 16003,
  ORDER_STOCK_NOT_ENOUGH = 16004,
  ORDER_STATUS_INVALID = 16005,
  ORDER_NOT_FOUND = 16006,
  PAY_TIMEOUT = 16007,
  PAY_AMOUNT_MISMATCH = 16008,
  DUPLICATE_OPERATION = 16009,
  CANNOT_CANCEL_ORDER = 16010,
  AFTERSALE_IN_PROGRESS = 16011,

  PRICING_RULE_NOT_FOUND = 17001,
  COUPON_UNAVAILABLE = 17002,
  COUPON_EXPIRED = 17003,

  ORDER_GRABBED_BY_OTHER = 18001,
  OUT_OF_ACCEPT_RANGE = 18002,
  RIDER_CANNOT_ACCEPT = 18003,
  ORDER_NOT_IN_POOL = 18004,

  REFUND_AMOUNT_EXCEED = 19001,
  AFTERSALE_DUPLICATE = 19002,
  AFTERSALE_STATUS_INVALID = 19003,
  AFTERSALE_NOT_FOUND = 19004,
  REFUND_EXECUTE_FAILED = 19005,

  BALANCE_NOT_ENOUGH = 20001,
  UNDER_MIN_WITHDRAWAL = 20002,
  WITHDRAWAL_DAILY_LIMIT = 20003,
  WITHDRAWAL_STATUS_INVALID = 20004,

  SMS_SEND_FAILED = 21001,
  PUSH_SEND_FAILED = 21002,

  CONFIG_NOT_FOUND = 22001,
  CONFIG_KEY_DUPLICATE = 22002,
  AREA_HAS_CHILDREN = 22003,

  BLACKLIST_ACCOUNT = 23001,
  BLACKLIST_IP = 23002,
}

export const ErrorCodeHttpStatus: Record<number, number> = {
  [ErrorCode.SUCCESS]: 200,

  [ErrorCode.PARAM_INVALID]: 400,
  [ErrorCode.DATA_NOT_FOUND]: 404,
  [ErrorCode.DATA_ALREADY_EXISTS]: 409,
  [ErrorCode.OPERATION_FAILED]: 500,
  [ErrorCode.SERVER_ERROR]: 500,

  [ErrorCode.RATE_LIMIT_EXCEEDED]: 429,
  [ErrorCode.REQUEST_FORMAT_ERROR]: 400,
  [ErrorCode.METHOD_NOT_ALLOWED]: 405,

  [ErrorCode.NOT_LOGGED_IN]: 401,
  [ErrorCode.TOKEN_INVALID]: 401,
  [ErrorCode.PERMISSION_DENIED]: 403,
  [ErrorCode.ACCOUNT_FROZEN]: 403,
  [ErrorCode.VERIFY_CODE_ERROR]: 400,
  [ErrorCode.TOO_FREQUENT]: 429,
  [ErrorCode.DAILY_LIMIT_REACHED]: 429,

  [ErrorCode.USER_PHONE_ALREADY_BOUND]: 409,
  [ErrorCode.USER_WX_AUTH_FAILED]: 400,
  [ErrorCode.USER_ADDRESS_LIMIT]: 400,
  [ErrorCode.USER_ADDRESS_NOT_FOUND]: 404,
  [ErrorCode.USER_ADDRESS_FORBIDDEN]: 403,

  [ErrorCode.MERCHANT_NOT_FOUND]: 404,
  [ErrorCode.MERCHANT_PASSWORD_ERROR]: 401,
  [ErrorCode.MERCHANT_FROZEN]: 403,
  [ErrorCode.MERCHANT_PHONE_REGISTERED]: 409,
  [ErrorCode.MERCHANT_AUDIT_NOT_PASSED]: 400,
  [ErrorCode.STORE_NOT_FOUND]: 404,
  [ErrorCode.STORE_FORBIDDEN]: 403,
  [ErrorCode.STORE_STATUS_INVALID]: 400,

  [ErrorCode.RIDER_NOT_FOUND]: 404,
  [ErrorCode.RIDER_PASSWORD_ERROR]: 401,
  [ErrorCode.RIDER_FROZEN]: 403,
  [ErrorCode.RIDER_PHONE_REGISTERED]: 409,
  [ErrorCode.RIDER_AUDIT_NOT_PASSED]: 400,
  [ErrorCode.RIDER_NOT_ONLINE]: 400,

  [ErrorCode.SMS_SEND_FAILED]: 500,

  [ErrorCode.BLACKLIST_ACCOUNT]: 403,
  [ErrorCode.BLACKLIST_IP]: 403,
};
