export enum OrderStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  CLOSED_UNPAID = 'CLOSED_UNPAID',
  DELIVERED = 'DELIVERED',
  COMPLETED = 'COMPLETED',
  AFTERSALE = 'AFTERSALE',
  REFUNDED = 'REFUNDED',
  PENDING_MERCHANT = 'PENDING_MERCHANT',
  MERCHANT_REJECTED = 'MERCHANT_REJECTED',
  MERCHANT_TIMEOUT = 'MERCHANT_TIMEOUT',
  PENDING_RIDER = 'PENDING_RIDER',
  PENDING_PICKUP = 'PENDING_PICKUP',
  DELIVERING = 'DELIVERING',
  PENDING_REVIEW = 'PENDING_REVIEW',
  PENDING_DISPATCH = 'PENDING_DISPATCH',
  CANCELLED = 'CANCELLED',
  RIDER_ACCEPTED = 'RIDER_ACCEPTED',
  ON_THE_WAY = 'ON_THE_WAY',
  IN_PROGRESS = 'IN_PROGRESS',
}

export enum OrderType {
  PRODUCT = 'PRODUCT',
  ERRAND = 'ERRAND',
}

export enum ErrandServiceType {
  DELIVER = 'DELIVER',
  PICKUP = 'PICKUP',
  BUY = 'BUY',
  ERRAND = 'ERRAND',
}

export enum UserType {
  MOBILE = 'mobile',
  ADMIN = 'admin',
}

export enum ErrorCode {
  SUCCESS = 0,
  PARAM_INVALID = 10001,
  DATA_NOT_FOUND = 10002,
  DATA_ALREADY_EXISTS = 10003,
  OPERATION_FAILED = 10004,
  SERVER_ERROR = 10005,
  RATE_LIMIT_EXCEEDED = 10100,
  REQUEST_FORMAT_ERROR = 10101,
  NOT_LOGGED_IN = 11001,
  TOKEN_INVALID = 11002,
  PERMISSION_DENIED = 11003,
  ACCOUNT_FROZEN = 11004,
  VERIFY_CODE_ERROR = 11005,
  TOO_FREQUENT = 11006,
  DAILY_LIMIT_REACHED = 11007,
}
